import { randomBoolean } from './utils/random-boolean';
import { generateCustomLenghtId } from './utils/generate-id';
import { fakeData } from './utils/faker';
import { nanoid } from 'nanoid';
import { SeedTable } from './Table.interface';
import {
  generateNumericalMax,
  getRandomFromList,
  randomDateBetween,
} from './utils';

// you can use all of faker methods, also you can use your own methods
// to generate data
// there are some utils methods to help you to generate data

export const seed: SeedTable[] = [
  {
    table: 'prestamo_alumno',
    count: 200,
    columns: [
      'carnet_alumno',
      'codigo_libro',
      'fecha_prestamo',
      'fecha_devolucion',
      'codigo_prestamo',
      'cantidadprestamo',
    ],
    values: () => [
      '#-0-carnet',
      '#-1-codigolibro',
      randomDateBetween(new Date(2010, 0, 1), new Date()),
      randomBoolean()
        ? randomDateBetween(new Date(2010, 0, 1), new Date())
        : null,
      nanoid(5),
      generateNumericalMax(10),
    ],
    dependencies: ['alumno', 'libro'],
    isDependent: true,
    dependentOrder: 2,
  },
  {
    table: 'libro',
    columns: [
      'codigolibro',
      'titulolibro',
      'existencia',
      'codigocategoria',
      'precio',
      'codigoautor',
    ],
    isDependent: true,
    dependentOrder: 1,
    dependencies: ['categorialibro', 'autor'],
    generateFromArray: true,
    array: [
      ['La casa de Bernarda Alba'],
      ['La colmena'],
      ['El gato negro'],
      ['El aleph'],
      ['Rayuela'],
      ['La tregua'],
      ['La guerra de los mundos'],
      ['La naranja mecánica'],
      ['La conjura de los necios'],
      ['El ocho'],
      ['El día del chacal'],
      ['El club de la lucha'],
      ['El código Da Vinci'],
      ['Los pilares de la tierra'],
      ['La catedral del mar'],
      ['La sombra del viento'],
      ['El cementerio de Praga'],
      ['La cabaña del tío Tom'],
      ['La llamada de lo salvaje'],
      ['El señor de las moscas'],
      ['Matar a un ruiseñor'],
      ['El nombre de la rosa'],
      ['La hoguera de las vanidades'],
      ['Crónicas marcianas'],
      ['Dune'],
      ['Fahrenheit 451'],
      ['La isla misteriosa'],
      ['La vuelta al mundo en ochenta días'],
      ['La isla del tesoro'],
      ['Robinson Crusoe'],
      ['La Odisea'],
      ['La Ilíada'],
      ['Las aventuras de Tom Sawyer'],
      ['Las aventuras de Huckleberry Finn'],
      ['El gran Gatsby'],
      ['Las uvas de la ira'],
      ['De ratones y hombres'],
      ['La perla'],
      ['El amor en los tiempos del cólera'],
      ['Cien años de soledad'],
      ['El coronel no tiene quien le escriba'],
      ['El general en su laberinto'],
      ['El túnel'],
      ['La ciudad y los perros'],
      ['La muerte de Artemio Cruz'],
      ['Pedro Páramo'],
      ['El llano en llamas'],
      ['El extranjero'],
      ['El proceso'],
      ['El castillo'],
      ['La metamorfosis'],
      ['El jardín de los senderos que se bifurcan'],
      ['La insoportable levedad del ser'],
      ['El hombre invisible'],
      ['La mujer en la ventana'],
      ['El psicoanalista'],
      ['El código enigma'],
      ['La caída de los gigantes'],
      ['El invierno del mundo'],
      ['El umbral de la eternidad'],
      ['El niño con el pijama de rayas'],
      ['La ladrona de libros'],
      ['La luz que no puedes ver'],
      ['El laberinto de los espíritus'],
      ['La casa de las miniaturas'],
      ['La caza'],
      ['La chica de nieve'],
      ['Un pequeño favor'],
      ['La chica del tren'],
      ['El libro de los Baltimore'],
      ['Un hombre llamado Ove'],
      ['La verdad sobre el caso Harry Quebert'],
      ['El psicoanalista'],
      ['La sombra del viento'],
      ['El código Da Vinci'],
      ['Los pilares de la tierra'],
      ['La catedral del mar'],
      ['La hoguera de las vanidades'],
      ['La isla misteriosa'],
      ['La vuelta al mundo en ochenta días'],
      ['La isla del tesoro'],
      ['Robinson Crusoe'],
      ['La Odisea'],
      ['La Ilíada'],
      ['Las aventuras de Tom Sawyer'],
      ['Las aventuras de Huckleberry Finn'],
      ['Las uvas de la ira'],
      ['De ratones y hombres'],
      ['El nombre de la rosa'],
      ['La perla'],
      ['Cien años de soledad'],
      ['El amor en los tiempos del cólera'],
      ['El coronel no tiene quien le escriba'],
      ['Cien años de soledad'],
      ['El Aleph'],
      ['Rayuela'],
      ['La tregua'],
      ['El amor en los tiempos del cólera'],
      ['La ciudad y los perros'],
      ['La casa de los espíritus'],
      ['Los pasos perdidos'],
      ['La invención de Morel'],
      ['La fiesta del chivo'],
      ['Pedro Páramo'],
      ['La sombra del viento'],
      ['El otoño del patriarca'],
      ['El túnel'],
      ['El hombre en busca de sentido'],
      ['El perfume'],
      ['1984'],
      ['Fahrenheit 451'],
      ['Un mundo feliz'],
      ['Doce cuentos peregrinos'],
      ['La muerte de Artemio Cruz'],
      ['Como agua para chocolate'],
      ['La guerra del fin del mundo'],
      ['Las batallas en el desierto'],
      ['Los cachorros'],
      ['El coronel no tiene quien le escriba'],
      ['La insoportable levedad del ser'],
      ['El viejo y el mar'],
      ['El lobo estepario'],
      ['El proceso'],
      ['El castillo'],
      ['El extranjero'],
      ['El gran Gatsby'],
      ['Matar a un ruiseñor'],
      ['Los miserables'],
      ['Madame Bovary'],
      ['La iliada'],
      ['La odisea'],
      ['La divina comedia'],
      ['Hamlet'],
      ['El rey Lear'],
      ['Romeo y Julieta'],
      ['El mercader de Venecia'],
      ['Orgullo y prejuicio'],
      ['El retrato de Dorian Gray'],
      ['Drácula'],
      ['Frankenstein'],
      ['El hombre invisible'],
      ['La isla del tesoro'],
      ['Robinson Crusoe'],
      ['Moby Dick'],
      ['El conde de Montecristo'],
      ['Los tres mosqueteros'],
      ['La vuelta al mundo en ochenta días'],
      ['Viaje al centro de la tierra'],
      ['Veinte mil leguas de viaje submarino'],
      ['El principito'],
      ['Crimen y castigo'],
      ['Los hermanos Karamazov'],
      ['Guerra y paz'],
      ['Anna Karenina'],
      ['La montaña mágica'],
      ['Ulises'],
      ['Dublineses'],
      ['Retrato del artista adolescente'],
      ['La inmortalidad'],
      ['Las olas'],
      ['La metamorfosis'],
      ['La náusea'],
      ['La peste'],
      ['El extranjero'],
      ['El túnel'],
      ['La muerte de Ivan Ilich'],
      ['El maestro y Margarita'],
      ['El jugador'],
      ['El proceso'],
      ['Cien años de soledad'],
      ['La hojarasca'],
      ['El amor en los tiempos del cólera'],
      ['Crónica de una muerte anunciada'],
      ['El coronel no tiene quien le escriba'],
      ['El otoño del patriarca'],
      ['Los funerales de la Mamá Grande'],
      ['La vorágine'],
      ['María'],
      ['La vorágine'],
      ['María'],
      ['El señor presidente'],
      ['El árbol de la ciencia'],
      ['Niebla'],
      ['La Regenta'],
      ['Fortunata y Jacinta'],
      ['La familia de Pascual Duarte'],
      ['El espejo africano'],
      ['La rebelión de las masas'],
      ['La deshumanización del arte'],
      ['Ensayos'],
      ['El hombre en busca de sentido'],
      ['Así habló Zaratustra'],
      ['La genealogía de la moral'],
      ['El anticristo'],
    ],
    values: () => {
      return [
        nanoid(5),
        '$0',
        generateNumericalMax(1000),
        '#-0-codigocategoria',
        generateNumericalMax(100),
        '#-1-codigoautor',
      ];
    },
  },
  {
    table: 'categorialibro',
    columns: ['codigocategoria', 'nombrecategoria'],
    generateFromArray: true,
    values: () => [nanoid(5), '$0'],
    array: [
      ['Novela'],
      ['Poesía'],
      ['Teatro'],
      ['Cuento'],
      ['Biografía'],
      ['Ensayo'],
      ['Ciencia Ficción'],
      ['Fantasía'],
      ['Terror'],
      ['Autoayuda'],
      ['Religión'],
      ['Accion'],
      ['Aventura'],
      ['Comedia'],
      ['Crimen'],
      ['Drama'],
      ['Fantasía'],
      ['Historia'],
      ['Misterio'],
      ['Policíaco'],
      ['Romance'],
      ['Suspenso'],
      ['Thriller'],
      ['Western'],
      ['Infantil'],
      ['Juvenil'],
      ['Cuentos'],
    ],
  },
  {
    count: 75,
    table: 'autor',
    columns: [
      'codigoautor',
      'nombreautor',
      'apellidoautor',
      'nacionalidad',
      'fechanacimiento',
    ],
    values: () => {
      return [
        nanoid(5),
        fakeData.name.firstName(),
        fakeData.name.lastName(),
        fakeData.address.streetAddress(),
        randomDateBetween(new Date(1990, 0, 1), new Date()),
      ];
    },
  },

  {
    table: 'alumno',
    count: 100,
    columns: [
      'carnet',
      'nombre',
      'apellido',
      'direccion',
      'fechanacimiento',
      'fechaingreso',
      'genero',
      'estado',
    ],
    values: () => {
      return [
        nanoid(5),
        fakeData.name.firstName(),
        fakeData.name.lastName(),
        fakeData.address.streetAddress(),
        randomDateBetween(new Date(1990, 0, 1), new Date()),
        randomDateBetween(new Date(2010, 0, 1), new Date()),
        getRandomFromList(['masculino', 'femenino']),
        randomBoolean(),
      ];
    },
  },
];
